### ISSUE TITLE
Can't resolve ethers/lib/utils

### ISSUE THREAD

**Issue by pepoospina** [Seth-McKilla/nextjs-wagmi#1]
I'm getting this error from a clean installation.

![image](https://user-images.githubusercontent.com/3278772/168618891-6b504984-ab96-4911-a484-ccf47761f2cf.png)

Tried using Node 14 and 17, but I got the same result.

**Comment by Seth-McKilla** [comment]
Thanks for sharing this info! I'll look into this and get a patch out soon 👍

**Comment by KaladinStormBlessed16** [comment]
Hello @pepoospina @Seth-McKilla 
I'm facing the same issue. did you manage to fix it?

**Comment by yusufferdogan** [comment]
> Hello @pepoospina @Seth-McKilla I'm facing the same issue. did you manage to fix it?

just add

    "ethers":"5.7.0"
to dev dependencies

**Comment by liyang51827** [comment]
Hello, @yusufferdogan 
I had met the same problem with @pepoospina , and your suggestion saved my day.
Thanks.
@Seth-McKilla I think this issue can be closed now.
